export const LOAD_PROFILES = 'LOAD_PROFILES';
export const GET_PROFILES = 'GET_PROFILES';
export const ADD_PROFILE = 'ADD_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';